from __future__ import annotations

import re

from ceilingfan_esphome.esphome import (
    _identifier,
    bridge_hostname,
    command_waveform,
    create_secrets,
    ensure_web_password,
    label_entity_warnings,
    render_firmware,
    require_command,
    validation_steps,
    write_firmware,
)
import pytest

from ceilingfan_esphome.models import CeilingFanError, DeviceProfile, LearnedWaveform
from ceilingfan_esphome.protocols import build_cjoy_profile


def waveform() -> LearnedWaveform:
    return LearnedWaveform(
        preamble_us=[1000],
        frame_us=[1000, -300, 300],
        gap_us=7000,
        repetitions=3,
        trailing_space_us=300,
        confidence=1.0,
        observations=3,
    )


def test_command_waveform_produces_mark_space_pairs() -> None:
    result = command_waveform(waveform())

    assert result[:4] == [1000, -7000, 1000, -300]
    assert result[-1] == -300
    assert len(result) % 2 == 0
    assert all(value > 0 for value in result[::2])
    assert all(value < 0 for value in result[1::2])


def test_command_waveform_replaces_terminal_space_with_frame_gap() -> None:
    command = waveform()
    command = LearnedWaveform(
        **{**command.__dict__, "frame_us": [1000, -300, 300, -1000]}
    )

    result = command_waveform(command)

    assert -7000 in result
    assert all(value > 0 for value in result[::2])
    assert all(value < 0 for value in result[1::2])


def test_render_firmware_exposes_supported_entities() -> None:
    profile = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={
            "fan_off": waveform(),
            "fan_speed_1": waveform(),
            "fan_speed_2": waveform(),
            "light_off": waveform(),
            "light_on": waveform(),
        },
    )

    rendered = render_firmware(profile)

    assert "name: bedroom-ceiling-fan" in rendered
    assert "frequency: 433.92000MHz" in rendered
    assert "speed_count: 2" in rendered
    assert "id: ceiling_fan" in rendered
    assert "id: ceiling_light" in rendered
    assert "name: Ceiling fan light" in rendered
    assert "Generated by ceilingfan-esphome" in rendered


def test_render_firmware_exposes_multiple_profiles_on_one_radio() -> None:
    bedroom = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        output_power_dbm=1,
        commands={
            "fan_off": waveform(),
            "fan_speed_1": waveform(),
            "light_off": waveform(),
            "light_on": waveform(),
        },
    )
    office = DeviceProfile(
        name="Office fan",
        frequency_hz=315_000_000,
        output_power_dbm=5,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )

    rendered = render_firmware([bedroom, office], bridge_name="Upstairs RF bridge")

    assert "name: upstairs-rf-bridge" in rendered
    assert "friendly_name: Upstairs RF bridge" in rendered
    assert "id: bedroom_ceiling_fan_fan" in rendered
    assert "name: Bedroom ceiling fan" in rendered
    assert "id: office_fan_fan" in rendered
    assert "name: Office fan" in rendered
    assert "id: bedroom_ceiling_fan_light" in rendered
    assert "frequency: 433920000" in rendered
    assert "frequency: 315000000" in rendered
    assert "output_power: 1" in rendered
    assert "output_power: 5" in rendered
    assert "id(radio).set_frequency(frequency)" in rendered
    assert rendered.count("\nfan:\n") == 1
    assert rendered.count("\nlight:\n") == 1
    assert "non_blocking: false" in rendered


def test_render_firmware_limits_fallback_ssid_to_32_bytes() -> None:
    profile = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )

    rendered = render_firmware(
        profile, bridge_name="Ceiling fan bridge with a very long friendly name"
    )

    assert "fallback_ssid: ceiling-fan-bridge-with fallback" in rendered
    assert 'ssid: "${fallback_ssid}"' in rendered


def test_render_firmware_exposes_absolute_brightness_levels() -> None:
    profile = DeviceProfile(
        name="Inspire bedroom fan",
        frequency_hz=433_920_000,
        commands={
            "fan_off": waveform(),
            "fan_speed_1": waveform(),
            "light_off": waveform(),
            **{f"light_brightness_{level}": waveform() for level in range(1, 9)},
        },
    )

    rendered = render_firmware(profile)

    assert "platform: monochromatic" in rendered
    assert "type: float" in rendered
    assert "state * 8 + 0.5f" in rendered
    assert "gamma_correct: 1.0" in rendered
    assert "default_transition_length: 0s" in rendered
    assert "case 8: return" in rendered


def test_render_firmware_rejects_incomplete_brightness_levels() -> None:
    profile = DeviceProfile(
        name="Incomplete dimmer",
        frequency_hz=433_920_000,
        commands={
            "light_off": waveform(),
            "light_brightness_1": waveform(),
            "light_brightness_3": waveform(),
        },
    )

    with pytest.raises(CeilingFanError, match="contiguous light_brightness_N"):
        render_firmware(profile)


def test_render_firmware_rejects_duplicate_profile_identifiers() -> None:
    first = DeviceProfile(
        name="Office fan",
        frequency_hz=433_920_000,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )
    second = DeviceProfile(
        name="Office-fan",
        frequency_hz=433_920_000,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )

    with pytest.raises(CeilingFanError, match="unique identifiers"):
        render_firmware([first, second])


def test_render_firmware_exposes_stateful_cjoy_adapter() -> None:
    profile = build_cjoy_profile("CJOY bedroom", 0x175D0310)

    rendered = render_firmware(profile)

    assert "id: cjoy_phase" in rendered
    assert "restore_value: yes" in rendered
    assert "speed_count: 6" in rendered
    assert "std::vector<int32_t> dynamic_waveform" in rendered
    assert "0x175D0310" in rendered
    assert "CJOY light toggle" in rendered
    assert "CJOY dimmer down" in rendered
    assert "CJOY dimmer up" in rendered
    assert "CJOY synchronize RF phase" in rendered
    assert rendered.count("id: transmit_command") >= 5
    assert "\nlight:\n" not in rendered


def test_render_firmware_keeps_cjoy_phase_per_profile() -> None:
    first = build_cjoy_profile("Bedroom CJOY", 0x175D0310)
    second = build_cjoy_profile("Office CJOY", 0x12345678)

    rendered = render_firmware([first, second])

    assert "id: bedroom_cjoy_cjoy_phase" in rendered
    assert "id: office_cjoy_cjoy_phase" in rendered
    assert "name: Bedroom CJOY" in rendered
    assert "name: Office CJOY" in rendered


def test_render_firmware_exposes_relative_raw_commands_as_buttons() -> None:
    profile = DeviceProfile(
        name="Inspire Nashi",
        frequency_hz=433_920_000,
        commands={
            "fan_toggle": waveform(),
            "fan_speed_1": waveform(),
            "light_toggle": waveform(),
            "dimmer_down": waveform(),
            "color_temperature_warm": waveform(),
        },
    )

    rendered = render_firmware(profile)

    assert "name: Inspire Nashi fan toggle" in rendered
    assert "name: Inspire Nashi fan speed 1" in rendered
    assert "name: Inspire Nashi light toggle" in rendered
    assert "name: Inspire Nashi dimmer down" in rendered
    assert "name: Inspire Nashi color temperature warm" in rendered
    assert "\nfan:\n" not in rendered
    assert "\nlight:\n" not in rendered


def test_render_firmware_web_ui_is_opt_in() -> None:
    profile = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )

    plain = render_firmware(profile)
    with_ui = render_firmware(profile, web_ui=True)

    assert "web_server:" not in plain
    assert "web_server:" in with_ui
    assert "password: !secret web_password" in with_ui


def test_create_secrets_includes_web_password(tmp_path) -> None:
    path = tmp_path / "secrets.yaml"

    create_secrets(path, "network", "wifi-password")

    assert "web_password:" in path.read_text(encoding="utf-8")


def test_ensure_web_password_appends_exactly_once(tmp_path) -> None:
    path = tmp_path / "secrets.yaml"
    with pytest.raises(CeilingFanError, match="secrets not found"):
        ensure_web_password(path)

    path.write_text('api_encryption_key: "value"\n', encoding="utf-8")
    ensure_web_password(path)
    first = path.read_text(encoding="utf-8")
    ensure_web_password(path)

    assert "web_password:" in first
    assert path.read_text(encoding="utf-8") == first


def test_render_firmware_advertises_discovery_project_metadata() -> None:
    profile = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )

    rendered = render_firmware(profile)

    assert "project:" in rendered
    assert "name: adrinavarro.ceilingfan-esphome" in rendered


def test_write_firmware_returns_the_final_bridge_hostname(tmp_path) -> None:
    profile = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={"fan_off": waveform(), "fan_speed_1": waveform()},
    )
    profile_path = tmp_path / "bedroom.yaml"
    profile.save(profile_path)

    hostname = write_firmware(
        profile_path, tmp_path / "generated.yaml", bridge_name="Home RF bridge"
    )

    assert hostname == "home-rf-bridge"
    assert bridge_hostname([profile]) == "bedroom-ceiling-fan"


def test_label_entity_warnings_flag_configurations_that_create_no_entity() -> None:
    assert label_entity_warnings(["fan_off", "fan_speed_1", "fan_speed_2"]) == []

    speed_without_off = label_entity_warnings(["fan_speed_1", "fan_speed_2"])
    assert any("fan_off" in warning for warning in speed_without_off)

    typo = label_entity_warnings(["fan_speed1", "fan_off"])
    assert any("typo" in warning and "fan_speed_1" in warning for warning in typo)

    light_on_only = label_entity_warnings(["light_on"])
    assert any("light_off" in warning for warning in light_on_only)

    broken_brightness = label_entity_warnings(
        ["light_off", "light_brightness_1", "light_brightness_3"]
    )
    assert any("contiguous" in warning for warning in broken_brightness)

    sparse_speeds = label_entity_warnings(["fan_off", "fan_speed_1", "fan_speed_3"])
    assert any("not contiguous" in warning for warning in sparse_speeds)


def test_validation_steps_cover_every_generated_entity() -> None:
    bedroom = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={
            "fan_off": waveform(),
            "fan_speed_1": waveform(),
            "fan_speed_2": waveform(),
            "light_off": waveform(),
            "light_brightness_1": waveform(),
            "light_brightness_2": waveform(),
            "fan_toggle": waveform(),
        },
    )
    office = build_cjoy_profile("Office CJOY", 0x175D0310)
    profiles = [bedroom, office]

    rendered = render_firmware(profiles, bridge_name="Home RF bridge")
    steps = validation_steps(profiles)

    # ESPHome project names are always author.project, so the dot filters the
    # discovery metadata out of the entity-name matches.
    entity_names = [
        name
        for name in re.findall(r"^    name: (.+)$", rendered, re.MULTILINE)
        if "." not in name
    ]
    rendered_object_ids = {_identifier(name) for name in entity_names}
    assert rendered_object_ids == {step.object_id for step in steps}

    validated_commands = {(step.profile_name, step.command) for step in steps}
    for profile in profiles:
        for command in profile.command_names():
            assert (profile.name, command) in validated_commands


def test_validation_steps_send_absolute_states_and_synchronize_cjoy_first() -> None:
    bedroom = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={
            "fan_off": waveform(),
            "fan_speed_1": waveform(),
            "light_off": waveform(),
            "light_brightness_1": waveform(),
            "light_brightness_2": waveform(),
        },
    )
    steps = validation_steps([bedroom])
    by_command = {step.command: step for step in steps}
    assert by_command["fan_speed_1"].state is True
    assert by_command["fan_speed_1"].speed == 1
    assert by_command["fan_off"].state is False
    assert by_command["light_brightness_1"].brightness == 0.5
    assert by_command["light_brightness_2"].brightness == 1.0
    assert by_command["fan_off"].object_id == "ceiling_fan"
    assert by_command["light_off"].object_id == "ceiling_fan_light"

    cjoy_steps = validation_steps([build_cjoy_profile("Office CJOY", 0x175D0310)])
    assert cjoy_steps[0].command == "synchronize_rf_phase"
    assert cjoy_steps[0].entity_type == "button"
    assert cjoy_steps[0].object_id == "cjoy_synchronize_rf_phase"


def test_require_command_suggests_the_firmware_extra_for_esphome(monkeypatch) -> None:
    monkeypatch.setattr("ceilingfan_esphome.esphome.shutil.which", lambda name: None)

    with pytest.raises(CeilingFanError, match="uv sync --extra firmware"):
        require_command("esphome")
    with pytest.raises(CeilingFanError, match="rtl_sdr.$"):
        require_command("rtl_sdr")
