from __future__ import annotations

from ceilingfan_esphome.esphome import command_waveform, render_firmware
from ceilingfan_esphome.models import DeviceProfile, LearnedWaveform


def waveform() -> LearnedWaveform:
    return LearnedWaveform(
        preamble_us=[1000],
        frame_us=[1000, -300, 300],
        gap_us=7000,
        repetitions=3,
        trailing_space_us=300,
        confidence=1.0,
        observations=3,
    )


def test_command_waveform_produces_mark_space_pairs() -> None:
    result = command_waveform(waveform())

    assert result[:4] == [1000, -7000, 1000, -300]
    assert result[-1] == -300
    assert len(result) % 2 == 0
    assert all(value > 0 for value in result[::2])
    assert all(value < 0 for value in result[1::2])


def test_command_waveform_replaces_terminal_space_with_frame_gap() -> None:
    command = waveform()
    command = LearnedWaveform(
        **{**command.__dict__, "frame_us": [1000, -300, 300, -1000]}
    )

    result = command_waveform(command)

    assert -7000 in result
    assert all(value > 0 for value in result[::2])
    assert all(value < 0 for value in result[1::2])


def test_render_firmware_exposes_supported_entities() -> None:
    profile = DeviceProfile(
        name="Bedroom ceiling fan",
        frequency_hz=433_920_000,
        commands={
            "fan_off": waveform(),
            "fan_speed_1": waveform(),
            "fan_speed_2": waveform(),
            "light_off": waveform(),
            "light_on": waveform(),
        },
    )

    rendered = render_firmware(profile)

    assert "name: bedroom-ceiling-fan" in rendered
    assert "frequency: 433.92000MHz" in rendered
    assert "speed_count: 2" in rendered
    assert "name: Ceiling fan light" in rendered
    assert "Generated by ceilingfan-esphome" in rendered
