from __future__ import annotations

import re
import secrets
import shutil
import subprocess
from pathlib import Path

from .models import CeilingFanError, DeviceProfile, LearnedWaveform


def command_waveform(command: LearnedWaveform) -> list[int]:
    waveform: list[int] = []

    def append(duration: int) -> None:
        if not duration:
            return
        if waveform and (waveform[-1] > 0) == (duration > 0):
            if duration < 0:
                waveform[-1] = -max(abs(waveform[-1]), abs(duration))
            else:
                waveform[-1] += duration
            return
        waveform.append(duration)

    if command.preamble_us:
        for duration in command.preamble_us:
            append(duration)
        append(-command.gap_us)
    for repetition in range(command.repetitions):
        for duration in command.frame_us:
            append(duration)
        if repetition + 1 < command.repetitions:
            append(-command.gap_us)
    if not waveform:
        raise CeilingFanError("Cannot generate an empty RF waveform")
    if waveform[0] < 0:
        waveform.pop(0)
    if waveform[-1] > 0:
        append(-command.trailing_space_us)
    if len(waveform) % 2:
        raise CeilingFanError("Generated waveform does not contain mark/space pairs")
    return waveform


def _identifier(value: str) -> str:
    result = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return result or "ceiling_fan"


def _hostname(value: str) -> str:
    result = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return result or "ceiling-fan"


def render_firmware(profile: DeviceProfile) -> str:
    device_id = _hostname(profile.name)
    command_names = sorted(profile.commands)
    command_ids = {name: index for index, name in enumerate(command_names)}

    arrays = []
    cases = []
    for name in command_names:
        values = command_waveform(profile.commands[name])
        array_name = f"wave_{_identifier(name)}"
        formatted = ", ".join(str(value) for value in values)
        arrays.append(f"          static const int32_t {array_name}[] = {{{formatted}}};")
        cases.append(
            f"            case {command_ids[name]}: waveform = {array_name}; "
            f"length = sizeof({array_name}) / sizeof({array_name}[0]); break;"
        )

    entity_sections: list[str] = []
    speed_keys = sorted(
        (
            (int(match.group(1)), key)
            for key in command_names
            if (match := re.fullmatch(r"fan_speed_(\d+)", key))
        ),
        key=lambda item: item[0],
    )
    if "fan_off" in command_ids and speed_keys:
        speed_cases = "\n".join(
            f"                case {speed}: return {command_ids[key]};"
            for speed, key in speed_keys
        )
        entity_sections.append(
            f"""fan:
  - platform: template
    id: ceiling_fan
    name: Ceiling fan
    speed_count: {max(speed for speed, _ in speed_keys)}
    restore_mode: RESTORE_DEFAULT_OFF
    on_state:
      then:
        - script.execute:
            id: transmit_command
            command: !lambda |-
              if (!x->state) return {command_ids['fan_off']};
              switch (x->speed) {{
{speed_cases}
                default: return {command_ids[speed_keys[0][1]]};
              }}
"""
        )
    if "light_on" in command_ids and "light_off" in command_ids:
        entity_sections.append(
            f"""output:
  - platform: template
    id: ceiling_light_output
    type: binary
    write_action:
      - script.execute:
          id: transmit_command
          command: !lambda |-
            return state ? {command_ids['light_on']} : {command_ids['light_off']};

light:
  - platform: binary
    id: ceiling_light
    name: Ceiling fan light
    output: ceiling_light_output
    restore_mode: RESTORE_DEFAULT_OFF
"""
        )
    if not entity_sections:
        raise CeilingFanError(
            "No supported entities found. Label commands as fan_off/fan_speed_N "
            "or light_on/light_off."
        )

    array_block = "\n".join(arrays)
    case_block = "\n".join(cases)
    entities = "\n".join(entity_sections)
    return f"""# Generated by ceilingfan-esphome. Edit the profile, not this file.
substitutions:
  device_name: {device_id}
  friendly_name: {profile.name}

esphome:
  name: ${{device_name}}
  friendly_name: ${{friendly_name}}
  min_version: 2025.12.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${{friendly_name}} fallback"
    password: !secret fallback_password

captive_portal:

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

cc1101:
  id: radio
  cs_pin: GPIO14
  frequency: {profile.frequency_hz / 1_000_000:.5f}MHz
  modulation_type: {profile.modulation}
  symbol_rate: 5000
  output_power: {profile.output_power_dbm}

remote_transmitter:
  id: rf_transmitter
  pin: GPIO26
  carrier_duty_percent: 100%
  non_blocking: true
  on_transmit:
    then:
      - cc1101.begin_tx
  on_complete:
    then:
      - cc1101.set_idle

script:
  - id: transmit_command
    mode: queued
    parameters:
      command: int
    then:
      - lambda: |-
          const int32_t *waveform = nullptr;
          size_t length = 0;
{array_block}
          switch (command) {{
{case_block}
            default:
              ESP_LOGE("ceilingfan_esphome", "Unknown command %d", command);
              return;
          }}
          auto call = id(rf_transmitter).transmit();
          auto *data = call.get_data();
          for (size_t i = 0; i < length; i += 2) {{
            data->item(waveform[i], -waveform[i + 1]);
          }}
          call.perform();

{entities}"""


def write_firmware(profile_path: Path, output_path: Path) -> None:
    profile = DeviceProfile.load(profile_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_firmware(profile), encoding="utf-8")


def require_command(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise CeilingFanError(f"Required command not found: {name}")
    return path


def run_esphome(config: Path, device: str) -> None:
    executable = require_command("esphome")
    subprocess.run([executable, "run", str(config), "--device", device], check=True)


def create_secrets(path: Path, ssid: str, wifi_password: str) -> None:
    import base64

    path.parent.mkdir(parents=True, exist_ok=True)
    api_key = base64.b64encode(secrets.token_bytes(32)).decode("ascii")
    import json

    content = (
        f"wifi_ssid: {json.dumps(ssid)}\n"
        f"wifi_password: {json.dumps(wifi_password)}\n"
        f'fallback_password: "{secrets.token_urlsafe(18)}"\n'
        f'api_encryption_key: "{api_key}"\n'
        f'ota_password: "{secrets.token_urlsafe(24)}"\n'
    )
    path.write_text(content, encoding="utf-8")
    path.chmod(0o600)
